#!/bin/bash -e


BIN_DIR=/var/vcap/packages/broker/bin
export CFGDIR=/var/vcap/jobs/broker/config

export JAVA_HOME=/var/vcap/packages/jdk7
export PATH=$PATH:$JAVA_HOME/bin:$BIN_DIR
PIDFILE=${BIN_DIR}/kafka.pid

case $1 in
  start)
        ${BIN_DIR}/kafka-server-start.sh -daemon $CFGDIR/server.properties
        ps ax | grep -i 'kafka.\Kafka' | grep java | grep -v grep | awk '{print $1}' > ${PIDFILE}
        ;;
  stop)
        kill -9 `cat $PIDFILE`
		rm -f ${PIDFILE}
        ;;

  *)
        echo "Usage: kafka_ctl start|stop"

        ;;

esac
